"""empty message

Revision ID: de46f562d3b4
Revises: 
Create Date: 2023-02-28 11:14:53.018356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "de46f562d3b4"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("categories", schema=None) as batch_op:
        batch_op.alter_column(
            "type", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=True
        )

    with op.batch_alter_table("questions", schema=None) as batch_op:
        batch_op.alter_column(
            "question",
            existing_type=sa.TEXT(),
            type_=sa.String(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "answer", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=True
        )
        batch_op.drop_constraint("category", type_="foreignkey")
        batch_op.create_foreign_key(None, "categories", ["category"], ["id"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("questions", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(
            "category",
            "categories",
            ["category"],
            ["id"],
            onupdate="CASCADE",
            ondelete="SET NULL",
        )
        batch_op.alter_column(
            "answer", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=True
        )
        batch_op.alter_column(
            "question",
            existing_type=sa.String(),
            type_=sa.TEXT(),
            existing_nullable=True,
        )

    with op.batch_alter_table("categories", schema=None) as batch_op:
        batch_op.alter_column(
            "type", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=True
        )

    # ### end Alembic commands ###
